# Generated by Django 3.0.5 on 2020-04-23 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=240, null=True)),
                ('project_status', models.CharField(max_length=240, null=True)),
                ('project_due_datetime', models.DateTimeField(null=True)),
                ('project_created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('project_members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=240, null=True)),
                ('task_description', models.TextField(null=True)),
                ('due_datetime', models.DateTimeField(null=True)),
                ('task_created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('sub_task', models.CharField(max_length=240, null=True)),
                ('attachment_url', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('assignee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_for_project', to='home.Project')),
                ('task_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_i_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=240, null=True)),
                ('message_content', models.TextField(null=True)),
                ('message_created_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('received', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_i_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_i_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
